name: Black Duck Sca Scan with Arbitrary Params
                                                                                                                                                                                                                                         
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
                                                                                                                                                                                                                                         
jobs:
  blackduck-sca-scan:
    runs-on: [mac-arm-sh]
                                                                                                                                                                                                                                         
    defaults:
      run:
        working-directory: ${{ github.workspace }}/nodejs-npm

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'  # Specify Node version
   
    - name: Install dependencies
      run: npm install  

    - name: Build Project
      run: |
        npm rebuild
                                                                                                                                                                                                                                         
    - name: Black Duck Sca Scan with Arbitrary Params
      uses: blackduck-inc/black-duck-security-scan@v2
      with:
        blackducksca_url: ${{ vars.BLACKDUCKSCA_URL }}
        blackducksca_token: ${{ secrets.BLACKDUCKSCA_TOKEN }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        detect_args: "--detect.source.path=${{ github.workspace }}/nodejs-npm"
        detect_search_depth: 3
      env:
        DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
